- name: ENSURE THAT VSCODE AND XRDP ARE INSTALLED
  hosts: control
  gather_facts: no
  become: yes

  tasks:

    - name: ADD THE KEY FOR VSCODE
      rpm_key:
        state: present
        key: https://packages.microsoft.com/keys/microsoft.asc

    - name: ADD THE VSCODE RPM INFO
      copy:
        src: files/vscode_rpminfo
        dest: /etc/yum.repos.d/vscode.repo

    - name: ENSURE XRDP IS INSTALLED
      yum: name=xrdp

    - name: ENSURE LXDE IS INSTALLED
      yum: name=lxde

    - name: ENSURE LXDE IS CONFIGURED
      shell: echo lxsession -s LXDE -e LXDE > /home/{{ user }}/.xsession

    - name: ENSURE VSCODE IS INSTALLED
      yum: name=code

    - name: Start xrdp service
      service: name=xrdp state=started
