---

- name: DISPLAY CONTENTS OF THE FILE
  hosts: localhost
  connection: local
  gather_facts: no


  tasks:

    - name: DISPLAY THE CONTENTS OF  FILE 1
      command: cat $FILE1
      register: contents_file1

    - debug: var=contents_file1

    - name: DISPLAY THE CONTENTS OF  FILE 2
      command: cat $FILE2
      register: contents_file2

    - debug: var=contents_file2
