---

- name: DISPLAY CONTENTS OF THE FILE
  hosts: localhost
  connection: local
  gather_facts: no


  tasks:

    # - name: CONTENTS OF FILE 1
    #   debug:
    #     var: file1


    # - name: CONTENTS OF FILE 2
    #   debug:
    #     var: file2

    - name: DISPLAY THE NAME OF THE FILE
      command: echo $FILE1
      register: output

    - debug: var=output

    - name: DISPLAY THE CONTENTS OF THE FILE
      command: cat $FILE1
      register: contents

    - debug: var=contents
