---
- name: checkpoint existing configuration for rollback
  ios_command:
    commands:
      - command: "copy running-config flash:{{ ios_config_checkpoint_filename }}"
        prompt: ["? "]
        answer: "{{ ios_config_checkpoint_filename }}"
  when: ios_rollback_enabled

- name: load configuration onto target device
  block:
    - name: load config file contents
      set_fact:
        ios_config_text: "{{ lookup('network_template', ios_config_file) | join('\n') }}"
      when: ios_config_file is defined

    - name: create temp working dir
      file:
        path: "{{ ios_config_working_dir }}"
        state: directory
      run_once: true

    - name: template source config
      copy:
        content: "{{ ios_config_text }}"
        dest: "{{ ios_config_working_dir }}/{{ ios_config_temp_config_file }}"

    - name: load configuration file onto target device
      block:
        - name: enable the ios scp server
          cli:
            command: "{{ line }}"
          loop:
            - configure terminal
            - ip scp server enable
            - end
          loop_control:
            loop_var: line

        - name: copy configuration to device
          net_put:
            src: "{{ ios_config_working_dir }}/{{ ios_config_temp_config_file }}"
            dest: "flash:/{{ ios_config_temp_config_file }}"

        - name: generate ios diff
          cli:
            command: "show archive config differences flash:{{ ios_config_checkpoint_filename }} flash:{{ ios_config_temp_config_file }}"
          register: ios_config_diff

        - name: display config diff
          debug:
            msg: "{{ ios_config_diff.stdout.splitlines() }}"

        - name: replace current active configuration
          cli:
            command: "config replace flash:/{{ ios_config_temp_config_file }} force"
          when: not ansible_check_mode and ios_config_replace
          changed_when: ios_config_diff.stdout

        - name: merge current active configuration
          cli:
            command: "copy flash:/{{ ios_config_temp_config_file }} force"
          when: not ansible_check_mode and not ios_config_replace
          changed_when: ios_config_diff.stdout

        - name: remove uploaded configuration
          cli:
            command: "delete /force flash:/{{ ios_config_temp_config_file }}"

        - name: remove temp working dir
          file:
            path: "{{ ios_config_working_dir }}"
            state: absent
          run_once: true

      rescue:
        - name: remove uploaded configuration
          cli:
            command: "delete /force flash:/{{ ios_config_temp_config_file }}"

        - name: remove temp working dir
          file:
            path: "{{ ios_config_working_dir }}"
            state: absent
          run_once: true

        - name: set host failed
          fail:
            msg: "error loading configuration onto target device"

  rescue:
    - name: display message
      debug:
        msg: "error configuring device, starting rollback"
      when: ios_rollback_enabled

    - name: configuration rollback pre hook
      include_tasks: "{{ ios_configuration_rollback_pre_hook }}"
      when: ios_configuration_rollback_pre_hook is defined and ios_rollback_enabled

    - name: rollback configuration
      ios_command:
        commands:
          - command: "copy flash:/{{ ios_config_checkpoint_filename }} running-config"
            prompt: ["? "]
            answer: "running-config"

    - name: remove configuration checkpoint file
      cli:
        command: "delete /force flash:/{{ ios_config_checkpoint_filename }}"

    - name: configuration rollback post hook
      include_tasks: "{{ ios_configuration_rollback_post_hook }}"
      when: ios_configuration_rollback_post_hook is defined and ios_rollback_enabled

    - name: display message
      debug:
        msg: "successfully completed configuration rollback"
      when: ios_rollback_enabled

    - name: fail host due to config load error
      fail:
        msg: "error loading configuration onto target device"


- name: remove configuration checkpoint file
  cli:
    command: "delete /force flash:/{{ ios_config_checkpoint_filename }}"
  when: ios_rollback_enabled
